export const GET_AUCTION_ITEMS_SPINNER = 'GET_AUCTION_ITEMS_SPINNER';
export const GET_AUCTION_ITEMS_SUCCESS = 'GET_AUCTION_ITEMS_SUCCESS';
export const GET_AUCTION_ITEMS_FAILED = 'GET_AUCTION_ITEMS_FAILED';
export const GET_AUCTION_ITEM_SUCCESS = 'GET_AUCTION_ITEM_SUCCESS';
export const GET_AUCTION_ITEM_SPINNER = 'GET_AUCTION_ITEM_SPINNER';
export const GET_AUCTION_ITEM_FAILED = 'GET_AUCTION_ITEM_FAILED';
export const CLEAR_OLD_ITEM_DATA = 'CLEAR_OLD_ITEM_DATA';

export const UPDATE_BID_VALUE = 'UPDATE_BID_VALUE';
export const BID_LOADING = 'BID_LOADING';
export const BID_FAILED = 'BID_FAILED';
export const BID_SUCCESS = 'BID_SUCCESS';
