export const NAME_AND_MODAL_CHANGE = 'NAME_AND_MODAL_CHANGE';
export const INITIAL_PRICE_CHANGE = 'INITIAL_PRICE_CHANGE';
export const UPLOAD_PRODUCT_SPINNER = 'UPLOAD_PRODUCT_SPINNER';
export const UPLOAD_PRODUCT_SUCCESS = 'UPLOAD_PRODUCT_SUCCESS';
export const UPLOAD_PRODUCT_FAILED = 'UPLOAD_PRODUCT_FAILED';
export const UPDATE_CHANGED_DATES = 'UPDATE_CHANGED_DATES';
export const UPDATE_IMAGES = 'UPDATE_IMAGES';
